In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df=sns.load_dataset("titanic")

In [4]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [5]:
df.shape

(891, 15)

In [6]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [9]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [12]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [16]:
# We can extract object column which is not in the describe function
df.dtypes=='object'

survived       False
pclass         False
sex             True
age            False
sibsp          False
parch          False
fare           False
embarked        True
class          False
who             True
adult_male     False
deck           False
embark_town     True
alive           True
alone          False
dtype: bool

In [24]:
df[df.dtypes[df.dtypes=='object'].index]

        sex embarked    who  embark_town alive
0      male        S    man  Southampton    no
1    female        C  woman    Cherbourg   yes
2    female        S  woman  Southampton   yes
3    female        S  woman  Southampton   yes
4      male        S    man  Southampton    no
..      ...      ...    ...          ...   ...
886    male        S    man  Southampton    no
887  female        S  woman  Southampton   yes
888  female        S  woman  Southampton    no
889    male        C    man    Cherbourg   yes
890    male        Q    man   Queenstown    no

[891 rows x 5 columns]

In [41]:
df[df.dtypes[df.dtypes=='object'].index].describe()

         sex embarked  who  embark_town alive
count    891      889  891          889   891
unique     2        3    3            3     2
top     male        S  man  Southampton    no
freq     577      644  537          644   549

In [25]:
df[df.dtypes[df.dtypes=='int64'].index]

     survived  pclass  sibsp  parch
0           0       3      1      0
1           1       1      1      0
2           1       3      0      0
3           1       1      1      0
4           0       3      0      0
..        ...     ...    ...    ...
886         0       2      0      0
887         1       1      0      0
888         0       3      1      2
889         1       1      0      0
890         0       3      0      0

[891 rows x 4 columns]

In [27]:
df[df.dtypes[df.dtypes=='float64'].index]

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [28]:
## add some column
df['newcol']=0

In [29]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,newcol
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0

In [30]:
## Add new column in the specific place
df.insert(loc=3,column="food",value=11)

In [31]:
df

,survived,pclass,sex,food,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,newcol
0,0,3,male,11,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0
1,1,1,female,11,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
2,1,3,female,11,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,11,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0
4,0,3,male,11,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,11,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0
887,1,1,female,11,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0
888,0,3,female,11,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,0
889,1,1,male,11,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0
890,0,3,male,11,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0

In [37]:
#  It show the unique value of the column
pd.Categorical(df['pclass'])

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [40]:
df['class'].unique()

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [42]:
df[df['age']>18]

,survived,pclass,sex,food,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,newcol
0,0,3,male,11,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0
1,1,1,female,11,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
2,1,3,female,11,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,11,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0
4,0,3,male,11,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,11,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,0
886,0,2,male,11,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0
887,1,1,female,11,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0
889,1,1,male,11,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0
890,0,3,male,11,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0

In [45]:
df[(df['age']>18) & (df['pclass']==1)] # when we use and or operator we use samll bracket for seprate condition.

,survived,pclass,sex,food,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,newcol
1,1,1,female,11,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
3,1,1,female,11,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0
6,0,1,male,11,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,0
11,1,1,female,11,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,0
23,1,1,male,11,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,11,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False,0
872,0,1,male,11,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True,0
879,1,1,female,11,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,0
887,1,1,female,11,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0
889,1,1,male,11,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0

In [47]:
len(df[df['pclass']>1])

675

In [48]:
len(df['pclass'])

891

In [49]:
max(df['pclass'])

3

In [50]:
min(df['fare'])

0.0

In [51]:
max(df['fare'])

512.3292

In [54]:
df[df['fare']==max(df['fare'])]['embark_town']

258    Cherbourg
679    Cherbourg
737    Cherbourg
Name: embark_town, dtype: object

In [55]:
len(df[df['fare']==max(df['fare'])]['embark_town'])

3

In [58]:
## Slicing
df[['pclass','fare']][:15:2]

    pclass     fare
0        3   7.2500
2        3   7.9250
4        3   8.0500
6        1  51.8625
8        3  11.1333
10       3  16.7000
12       3   8.0500
14       3   7.8542

In [59]:
df.iloc[1:8,[0,1,2,3]] # it is used to select the column through the index

   survived  pclass     sex  food
1         1       1  female    11
2         1       3  female    11
3         1       1  female    11
4         0       3    male    11
5         0       3    male    11
6         0       1    male    11
7         0       3    male    11

## lecturer 72

In [61]:
df.head()

,survived,pclass,sex,food,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,newcol
0,0,3,male,11,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0
1,1,1,female,11,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
2,1,3,female,11,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,11,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0
4,0,3,male,11,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0

## We can drop the column use the drop method

In [65]:
df.drop("newcol",axis=1,inplace=True)

In [ ]:
df.drop(['parch','fare'],axis=1,inplace=1)

## Now we drop the data from the rowm

In [68]:
df.drop(3,axis=0,inplace=True)

In [69]:
df.head()

,survived,pclass,sex,food,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,11,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,11,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,11,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,11,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,11,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True

## Set index in any column

In [70]:
df.set_index('age')

,survived,pclass,sex,food,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
age,,,,,,,,,,,,,,,
22.0,0,3,male,11,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
38.0,1,1,female,11,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
26.0,1,3,female,11,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
35.0,0,3,male,11,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
NaN,0,3,male,11,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27.0,0,2,male,11,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
19.0,1,1,female,11,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
NaN,0,3,female,11,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
26.0,1,1,male,11,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
32.0,0,3,male,11,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## we can reset the index

In [71]:
df.reset_index()

,index,survived,pclass,sex,food,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,11,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,11,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,11,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,4,0,3,male,11,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
4,5,0,3,male,11,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,2,male,11,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
886,887,1,1,female,11,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
887,888,0,3,female,11,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
888,889,1,1,male,11,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
889,890,0,3,male,11,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## Now we can see the data in group

In [105]:
dt=pd.read_csv("Titanic.csv")
dt.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [96]:
g=dt.groupby(["Survived"])
g.sum()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Survived,,,,,,,,,,,
0,245412,1390,"Braund, Mr. Owen HarrisAllen, Mr. William Henr...",malemalemalemalemalemalemalefemalemalefemalema...,12985.50,304,181,A/5 2117137345033087717463349909A/5. 215134708...,12142.7199,E46C23 C25 C27B30C83F G73E31A5D26C110B58 B60D2...,SSQSSSSSQSSSCSSCSCSSSSSCSQCSSSCCSCSSCSSSSSCSSS...
1,151974,667,"Cumings, Mrs. John Bradley (Florence Briggs Th...",femalefemalefemalefemalefemalefemalefemalefema...,8219.67,162,159,PC 17599STON/O2. 3101282113803347742237736PP 9...,16551.2294,C85C123G6C103D56A6B78D33C52B28F33C23 C25 C27D1...,CSSSCSSSSCSQSSQCQCCCQQCSSSSCSSSSSSQSSSCSSSQSCS...

In [97]:
dt.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [110]:
m=df.groupby("Pclass")['Age'] ## Isme age ka mean value de rha hai har class ka
m.mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [102]:
t=df.groupby("Sex")['Fare']
t.count

Sex
female    512.3292
male      512.3292
Name: Fare, dtype: float64

In [111]:
df.loc[df['Fare'].idxmax(),'Name']

'Ward, Miss. Anna'

## Join 2 different Dataset

In [112]:
data1=df.iloc[1:8,[0,1,2,3]]

In [116]:
data2=df.iloc[1:8,[4,5,6,7]]

In [117]:
data1

,PassengerId,Survived,Pclass,Name
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry"
5,6,0,3,"Moran, Mr. James"
6,7,0,1,"McCarthy, Mr. Timothy J"
7,8,0,3,"Palsson, Master. Gosta Leonard"

In [118]:
data2

      Sex   Age  SibSp  Parch
1  female  38.0      1      0
2  female  26.0      0      0
3  female  35.0      1      0
4    male  35.0      0      0
5    male   NaN      0      0
6    male  54.0      0      0
7    male   2.0      3      1

## We can join teo dataset in three ways
## -- 1. concate()
## -- 2. merge()
## -- 3.join()

In [122]:
new=pd.concat([data1,data2])

In [123]:
new

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch
1,2.0,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",NaN,NaN,NaN,NaN
2,3.0,1.0,3.0,"Heikkinen, Miss. Laina",NaN,NaN,NaN,NaN
3,4.0,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",NaN,NaN,NaN,NaN
4,5.0,0.0,3.0,"Allen, Mr. William Henry",NaN,NaN,NaN,NaN
5,6.0,0.0,3.0,"Moran, Mr. James",NaN,NaN,NaN,NaN
6,7.0,0.0,1.0,"McCarthy, Mr. Timothy J",NaN,NaN,NaN,NaN
7,8.0,0.0,3.0,"Palsson, Master. Gosta Leonard",NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,female,38.0,1.0,0.0
2,NaN,NaN,NaN,NaN,female,26.0,0.0,0.0
3,NaN,NaN,NaN,NaN,female,35.0,1.0,0.0
4,NaN,NaN,NaN,NaN,male,35.0,0.0,0.0
5,NaN,NaN,NaN,NaN,male,NaN,0.0,0.0
6,NaN,NaN,NaN,NaN,male,54.0,0.0,0.0
7,NaN,NaN,NaN,NaN,male,2.0,3.0,1.0

In [129]:
new=pd.concat([data1,data2],axis=1)

In [130]:
new

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1

## 2. Merge : in this the column datatype is same otherwise it throw the error
## It work on the column match

In [131]:
a=pd.DataFrame({
    'key1':[1,2,3,4,5],
    'key2':[10,20,30,4,50],
    'key3':[5,4,3,2,1]
})
b=pd.DataFrame({
    'key1':['a','b','c','d','e'],
    'key5':['m','n','o','p','q'],
    'key6':[9,8,7,6,5]
})

In [134]:
a

   key1  key2  key3
0     1    10     5
1     2    20     4
2     3    30     3
3     4     4     2
4     5    50     1

In [135]:
b

  key1 key5  key6
0    a    m     9
1    b    n     8
2    c    o     7
3    d    p     6
4    e    q     5

In [144]:
a['key1']=a['key1'].astype(str)
new=pd.merge(a,b,how='right')
new

  key1  key2  key3 key5  key6
0    a   NaN   NaN    m     9
1    b   NaN   NaN    n     8
2    c   NaN   NaN    o     7
3    d   NaN   NaN    p     6
4    e   NaN   NaN    q     5

In [146]:
new=pd.merge(a,b,how='outer')
new

  key1  key2  key3 key5  key6
0    1  10.0   5.0  NaN   NaN
1    2  20.0   4.0  NaN   NaN
2    3  30.0   3.0  NaN   NaN
3    4   4.0   2.0  NaN   NaN
4    5  50.0   1.0  NaN   NaN
5    a   NaN   NaN    m   9.0
6    b   NaN   NaN    n   8.0
7    c   NaN   NaN    o   7.0
8    d   NaN   NaN    p   6.0
9    e   NaN   NaN    q   5.0

In [148]:
new=pd.merge(a,b,how='left')
new

  key1  key2  key3 key5  key6
0    1    10     5  NaN   NaN
1    2    20     4  NaN   NaN
2    3    30     3  NaN   NaN
3    4     4     2  NaN   NaN
4    5    50     1  NaN   NaN

In [150]:
new=pd.merge(a,b,how='inner')
new

Empty DataFrame
Columns: [key1, key2, key3, key5, key6]
Index: []

In [152]:
new=pd.merge(a,b,how='cross')
new

   key1_x  key2  key3 key1_y key5  key6
0       1    10     5      a    m     9
1       1    10     5      b    n     8
2       1    10     5      c    o     7
3       1    10     5      d    p     6
4       1    10     5      e    q     5
5       2    20     4      a    m     9
6       2    20     4      b    n     8
7       2    20     4      c    o     7
8       2    20     4      d    p     6
9       2    20     4      e    q     5
10      3    30     3      a    m     9
11      3    30     3      b    n     8
12      3    30     3      c    o     7
13      3    30     3      d    p     6
14      3    30     3      e    q     5
15      4     4     2      a    m     9
16      4     4     2      b    n     8
17      4     4     2      c    o     7
18      4     4     2      d    p     6
19      4     4     2      e    q     5
20      5    50     1      a    m     9
21      5    50     1      b    n     8
22      5    50     1      c    o     7
23      5    50     1      d    p     6
24      5    50     1      e    q     5

## 3. join : It work on the index match

In [ ]:
## in join the column name is different the use this type

In [187]:
a1=pd.DataFrame({
    'key1':[1,2,3,4,5],
    'key2':[10,20,30,4,50],
    'key3':[5,4,3,2,1]},
    index=[1,2,3,4,5]
)
b1=pd.DataFrame({
    'key11':[5,4,5,6,3],
    'key5':[10,20,30,40,50],
    'key6':[9,8,7,6,5]},
    index=[1,2,8,9,7]
)

In [188]:
a1

   key1  key2  key3
1     1    10     5
2     2    20     4
3     3    30     3
4     4     4     2
5     5    50     1

In [189]:
b1

   key11  key5  key6
1      5    10     9
2      4    20     8
8      5    30     7
9      6    40     6
7      3    50     5

In [190]:
new = a1.join(b1, how='inner')
print(new)

   key1  key2  key3  key11  key5  key6
1     1    10     5      5    10     9
2     2    20     4      4    20     8

In [192]:
new = a1.join(b1, how='left')
print(new)

   key1  key2  key3  key11  key5  key6
1     1    10     5    5.0  10.0   9.0
2     2    20     4    4.0  20.0   8.0
3     3    30     3    NaN   NaN   NaN
4     4     4     2    NaN   NaN   NaN
5     5    50     1    NaN   NaN   NaN

In [193]:
new = a1.join(b1, how='right')
print(new)

   key1  key2  key3  key11  key5  key6
1   1.0  10.0   5.0      5    10     9
2   2.0  20.0   4.0      4    20     8
8   NaN   NaN   NaN      5    30     7
9   NaN   NaN   NaN      6    40     6
7   NaN   NaN   NaN      3    50     5

In [200]:
new = a1.join(b1, how='outer')
print(new)

   key1  key2  key3  key11  key5  key6
1   1.0  10.0   5.0    5.0  10.0   9.0
2   2.0  20.0   4.0    4.0  20.0   8.0
3   3.0  30.0   3.0    NaN   NaN   NaN
4   4.0   4.0   2.0    NaN   NaN   NaN
5   5.0  50.0   1.0    NaN   NaN   NaN
7   NaN   NaN   NaN    3.0  50.0   5.0
8   NaN   NaN   NaN    5.0  30.0   7.0
9   NaN   NaN   NaN    6.0  40.0   6.0

## if column name is different then we join these type

In [201]:
a1=pd.DataFrame({
    'key1':[1,2,3,4,5],
    'key2':[10,20,30,4,50],
    'key3':[5,4,3,2,1]},
    index=[1,2,3,4,5]
)
b1=pd.DataFrame({
    'key1':[5,4,5,6,3],
    'key5':[10,20,30,40,50],
    'key6':[9,8,7,6,5]},
    index=[1,2,8,9,7]
)

In [202]:
new=a1.join(b1,how='right',lsuffix='_left',rsuffix='_right')
new

   key1_left  key2  key3  key1_right  key5  key6
1        1.0  10.0   5.0           5    10     9
2        2.0  20.0   4.0           4    20     8
8        NaN   NaN   NaN           5    30     7
9        NaN   NaN   NaN           6    40     6
7        NaN   NaN   NaN           3    50     5